runtime: go112

instance_class: B1
manual_scaling:
  instances: 1

includes:
    - secret.yaml

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 20